// Insights (articles) published by Assuage Attorneys.
//
// This module is the public entry point — keep importing from "@/data/insights".
// It is split three ways so that the content admin can regenerate content
// without touching hand-written code:
//   - insights.types.ts  types and category vocabulary (hand-written)
//   - insights.data.ts   the articles themselves (GENERATED by /admin)
//   - insights.ts        this file: helpers and re-exports (hand-written)
//
// Articles are written and published through the admin at /admin. Nothing
// published here constitutes legal advice.

export type { ContentBlock, Insight, InsightCategory } from "./insights.types";
export { insightCategories } from "./insights.types";

import type { Insight } from "./insights.types";
import { insights } from "./insights.data";

export { insights };

export function getInsight(slug: string): Insight | undefined {
  return insights.find((article) => article.slug === slug);
}

export function formatInsightDate(iso: string): string {
  const date = new Date(iso + "T00:00:00");
  return date.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}
