// Firm news for Assuage Attorneys.
//
// This module is the public entry point — keep importing from "@/data/news".
// It is split three ways so that the content admin can regenerate content
// without touching hand-written code:
//   - news.types.ts  types and label vocabulary (hand-written)
//   - news.data.ts   the news items themselves (GENERATED by /admin)
//   - news.ts        this file: helpers and re-exports (hand-written)
//
// TODO: the seeded items are placeholder announcements written for layout.
// Replace with real firm news before launch. Do not add rankings, awards or
// league table claims — see the firm's advertising obligations.

export type { NewsItem, NewsLabel } from "./news.types";
export { newsLabels } from "./news.types";

import { news } from "./news.data";

export { news };

export function formatNewsDate(iso: string): string {
  const date = new Date(iso + "T00:00:00");
  return date.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}
